language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

sudo: false

install: composer install --no-interaction

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --dev --no-interaction

script:
  - mkdir -p build/logs
  - composer test

after_success:
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then php vendor/bin/coveralls -v; fi;'
